#ifndef BH_LOG_HPP
#define BH_LOG_HPP

#define BH_LOG_MESSAGE_SIZ 1024 << 1

namespace bhLog
{
  enum Category // See SDL_LogCategory, SDL_log.h
  {
    LOG_CATEGORY_APPLICATION,
    LOG_CATEGORY_ERROR,
    LOG_CATEGORY_ASSERT,
    LOG_CATEGORY_SYSTEM,
    LOG_CATEGORY_AUDIO,
    LOG_CATEGORY_VIDEO,
    LOG_CATEGORY_RENDER,
    LOG_CATEGORY_INPUT,
    LOG_CATEGORY_TEST,
    LOG_CATEGORY_GPU,

    LOG_NUM_CATEGORIES
  };

  enum Priority // See SDL_LogPriority, SDL_log.h
  {
    LOG_PRIORITY_INVALID,
    LOG_PRIORITY_TRACE,
    LOG_PRIORITY_VERBOSE,
    LOG_PRIORITY_DEBUG,
    LOG_PRIORITY_INFO,
    LOG_PRIORITY_WARN,
    LOG_PRIORITY_ERROR,
    LOG_PRIORITY_CRITICAL,
    LOG_PRIORITY_COUNT,

    LOG_NUM_PRIORITIES
  };

  void Message(Category c, Priority p, const char* format, ...);
}

#endif //BH_LOG_HPP
